### ISSUE TITLE
Documentation For Gradle

### ISSUE THREAD

**Issue by RIGIK93** [Ancash/FancyCrafting#3]
Hello, tried to install with gradle. 
Used
```groovy
dependencies {
    implementation "de.ancash:fancycrafting:4.5.3"
}
```
It stack trace says there's no such package. Decided to check whether it's in  the maven repository at [mavenrepository.com](https://mvnrepository.com/search?q=de.ancash.fancycrafting&sort=relevance). No results. Either I'm doing something incorrectly or it's not public. Help, please.

**Comment by RIGIK93** [comment]
Additionaly, it would've been nicer if there was a gradle documentation on the spigotmc installation page

**Comment by Ancash** [comment]
try this![Screenshot_2022-12-26-12-10-21-724_com.android.chrome~2.jpg](https://user-images.githubusercontent.com/74488575/209543960-1fd3935b-3272-413f-9025-ed3255e14cf2.jpg)

you also have to use a pat.
read [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry) for more information.
